[package]
name = "spotify_cli"
version = "0.1.0"
authors = ["Julien LE THENO"]

[dependencies]
curl = "0.4.18"
serde_json = "1.0"
percent-encoding = "1.0.1"
clap = "2.32.0"
termion = "*"
tui = "*"
stderrlog = "0.4"
rand = "0.4"
failure = "0.1"
