[package]
name = "spotify_rust"
version = "0.0.3"
authors = ["Julien LE THENO"]

[dependencies]
spotify_api = {path = "spotify_api"}
clap = "2.32.0"
termion = "*"
tui = "*"
failure = "0.1"
text_io = "0.1.7"
webbrowser = "0.3.1"
term-painter = "0.2.4"